/**
 * Declarative sidebar layout for the ARGVUS documentation site.
 *
 * This file holds only data: which slugs go where, in what order, with which
 * sidebar-only label overrides and PT-BR translations. The assembly logic
 * that turns this data (plus whatever pages actually loaded from each
 * project) into a Starlight sidebar config lives in `starlight-sidebar-config.ts`.
 *
 * Edit this file to reorder sections, add a page to an explicit position, or
 * recategorize a component. Never edit `generated-sidebar.mjs` directly: it is
 * build output, regenerated by `npm run generate:sidebar`.
 */

/** A single sidebar link, resolved against a loaded content entry's slug. */
export interface LayoutLinkSpec {
  slug: string
  /** Sidebar-only label override. Omit to use the page's own (localized) title. */
  label?: string
  /** PT-BR translation of `label`. Only meaningful when `label` is set. */
  translations?: Record<string, string>
}

/** A sidebar group of links and/or nested groups. */
export interface LayoutGroupSpec {
  group: string
  translations?: Record<string, string>
  collapsed?: boolean
  items: LayoutNodeSpec[]
}

export type LayoutNodeSpec = LayoutLinkSpec | LayoutGroupSpec

export function isLayoutGroup(node: LayoutNodeSpec): node is LayoutGroupSpec {
  return 'group' in node
}

const OVERVIEW: Record<string, string> = { 'pt-BR': 'Visão geral' }

/**
 * `docs/getting-started` and its `installation` subtree, plus the
 * post-install "first configuration" page pulled out of `user-guide` so the
 * full onboarding flow (overview → requirements → install → first session →
 * first configuration) reads as one continuous path.
 */
export const GETTING_STARTED_SECTION: LayoutGroupSpec = {
  group: 'Getting Started',
  translations: { 'pt-BR': 'Primeiros passos' },
  collapsed: false,
  items: [
    { slug: 'docs/getting-started', label: 'Overview', translations: OVERVIEW },
    {
      slug: 'docs/getting-started/installation',
      label: 'Installation overview',
      translations: { 'pt-BR': 'Visão geral da instalação' },
    },
    { slug: 'docs/getting-started/installation/requirements' },
    { slug: 'docs/getting-started/installation/install' },
    { slug: 'docs/getting-started/installation/first-session' },
    { slug: 'docs/user-guide/getting-started' },
  ],
}

/**
 * Day-to-day usage, once ARGVUS is installed. FAQ, troubleshooting and
 * "where to configure things" live in `HELP_SECTION` instead: they are
 * reference material you reach for when something's wrong, not a feature you
 * read about while learning the desktop.
 */
export const USER_GUIDE_SECTION: LayoutGroupSpec = {
  group: 'User Guide',
  translations: { 'pt-BR': 'Guia do usuário' },
  collapsed: false,
  items: [
    { slug: 'docs/user-guide', label: 'Overview', translations: OVERVIEW },
    { slug: 'docs/user-guide/desktop' },
    { slug: 'docs/user-guide/applications' },
    { slug: 'docs/user-guide/sessions' },
    { slug: 'docs/user-guide/appearance' },
    { slug: 'docs/user-guide/localization' },
    { slug: 'docs/user-guide/hardware' },
    { slug: 'docs/user-guide/virtual-machines' },
    { slug: 'docs/user-guide/privacy-and-security' },
    { slug: 'docs/user-guide/where-to-configure' },
  ],
}

export const HELP_SECTION: LayoutGroupSpec = {
  group: 'Help',
  translations: { 'pt-BR': 'Ajuda' },
  collapsed: true,
  items: [
    { slug: 'docs/user-guide/faq' },
    {
      group: 'Troubleshooting',
      translations: { 'pt-BR': 'Solução de problemas' },
      items: [
        { slug: 'docs/user-guide/troubleshooting', label: 'Overview', translations: OVERVIEW },
        {
          slug: 'docs/user-guide/troubleshooting/installation',
          label: 'Installation',
          translations: { 'pt-BR': 'Instalação' },
        },
        {
          slug: 'docs/user-guide/troubleshooting/session-startup',
          label: 'Session startup',
          translations: { 'pt-BR': 'Início da sessão' },
        },
        {
          slug: 'docs/user-guide/troubleshooting/display-and-hyprland',
          label: 'Display and Hyprland',
          translations: { 'pt-BR': 'Display e Hyprland' },
        },
        // Own page title ("Graphics and virtual machines") already matches the
        // desired sidebar label, so no override is needed here.
        { slug: 'docs/user-guide/troubleshooting/graphics-and-virtual-machines' },
        {
          slug: 'docs/user-guide/troubleshooting/theme-and-wallpaper',
          label: 'Theme and wallpaper',
          translations: { 'pt-BR': 'Tema e wallpaper' },
        },
      ],
    },
  ],
}

export const REFERENCE_SECTION: LayoutGroupSpec = {
  group: 'Reference',
  translations: { 'pt-BR': 'Referência' },
  collapsed: true,
  items: [
    { slug: 'docs/reference', label: 'Overview', translations: OVERVIEW },
    { slug: 'docs/reference/argvus-config' },
    { slug: 'docs/reference/configuration-files' },
    { slug: 'docs/reference/file-locations' },
    { slug: 'docs/reference/environment-variables' },
    { slug: 'docs/reference/command-line' },
    { slug: 'docs/reference/services' },
    { slug: 'docs/reference/dbus-interfaces' },
    { slug: 'docs/reference/package-matrix' },
  ],
}

export const DEVELOPER_GUIDE_SECTION: LayoutGroupSpec = {
  group: 'Developer Guide',
  translations: { 'pt-BR': 'Guia do desenvolvedor' },
  collapsed: true,
  items: [
    { slug: 'docs/developer-guide', label: 'Overview', translations: OVERVIEW },
    {
      group: 'Architecture',
      translations: { 'pt-BR': 'Arquitetura' },
      items: [
        { slug: 'docs/developer-guide/architecture/overview' },
        { slug: 'docs/developer-guide/architecture/repository-roles' },
        { slug: 'docs/developer-guide/architecture/integration-map' },
        { slug: 'docs/developer-guide/architecture/runtime-lifecycle' },
        { slug: 'docs/developer-guide/architecture/configuration-and-state' },
      ],
    },
    {
      group: 'Subsystems',
      translations: { 'pt-BR': 'Subsistemas' },
      items: [
        { slug: 'docs/developer-guide/subsystems/session-and-systemd' },
        { slug: 'docs/developer-guide/subsystems/hyprland' },
        { slug: 'docs/developer-guide/subsystems/shell-surfaces' },
        { slug: 'docs/developer-guide/subsystems/appearance-and-themes' },
        { slug: 'docs/developer-guide/subsystems/greeter-lock-and-splash' },
        { slug: 'docs/developer-guide/subsystems/providers-and-services' },
      ],
    },
    {
      group: 'Component Reference',
      translations: { 'pt-BR': 'Referência de componentes' },
      items: [
        { slug: 'docs/developer-guide/component-reference/core-and-dispatcher' },
        { slug: 'docs/developer-guide/component-reference/providers-and-services' },
        { slug: 'docs/developer-guide/component-reference/ui-components' },
        { slug: 'docs/developer-guide/component-reference/integrations' },
        { slug: 'docs/developer-guide/component-reference/assets-and-packages' },
      ],
    },
    {
      group: 'Development',
      translations: { 'pt-BR': 'Desenvolvimento' },
      items: [
        { slug: 'docs/developer-guide/development/environment' },
        { slug: 'docs/developer-guide/development/contributing' },
        { slug: 'docs/developer-guide/development/translations' },
        { slug: 'docs/developer-guide/development/packaging' },
      ],
    },
  ],
}

export interface ComponentCategorySpec {
  key: string
  label: string
  translations: Record<string, string>
  /** `site-config.json` repository keys, in the order they should appear within this category. */
  repositories: string[]
}

/**
 * Maps every non-root documentation project to one user-facing category.
 * A project configured in `site-config.json` but missing from this map still
 * gets a sidebar entry (see `buildComponentCategories` in
 * `starlight-sidebar-config.ts`); it is placed in a trailing "Other
 * components" group and logged with `console.warn`, so recategorizing a new
 * project is as simple as adding its repository key to one list below.
 */
export const COMPONENT_CATEGORIES: ComponentCategorySpec[] = [
  {
    key: 'session-login',
    label: 'Session & Login',
    translations: { 'pt-BR': 'Sessão e login' },
    repositories: [
      'argvus-greeter',
      'argvus-lock',
      'argvus-session',
      'argvus-boot-splash',
      'argvus-accounts',
    ],
  },
  {
    key: 'desktop-shell',
    label: 'Desktop Shell',
    translations: { 'pt-BR': 'Shell do desktop' },
    repositories: [
      'argvus-taskbar',
      'argvus-taskbar-calendar',
      'argvus-launcher',
      'argvus-notifications',
      'argvus-removable-devices',
      'argvus-waybar',
      'argvus-portal',
    ],
  },
  {
    key: 'system-settings',
    label: 'System & Settings',
    translations: { 'pt-BR': 'Sistema e configurações' },
    repositories: [
      'argvus-control-center',
      'argvus-control-panel',
      'argvus-display',
      'argvus-network',
      'argvus-power',
      'argvus-firewall',
      'argvus-i18n',
    ],
  },
  {
    key: 'appearance-assets',
    label: 'Appearance & Assets',
    translations: { 'pt-BR': 'Aparência e recursos visuais' },
    repositories: ['argvus-appearance', 'argvus-themes', 'argvus-icons', 'argvus-fonts', 'argvus-wallpapers'],
  },
  {
    key: 'apps-tools',
    label: 'Apps & Tools',
    translations: { 'pt-BR': 'Aplicativos e ferramentas' },
    repositories: [
      'argvus-terminal',
      'argvus-system-monitor',
      'argvus-tui',
      'argvus-game-snake',
    ],
  },
]

/**
 * Repositories shown as their own top-level sidebar group instead of inside a
 * component category. Hyprland owns the keyboard shortcuts, which users look
 * for first, so it sits right after the User Guide.
 */
export const TOP_LEVEL_REPOSITORIES: string[] = ['argvus-hyprland']

export const OTHER_COMPONENTS_GROUP = {
  label: 'Other components',
  translations: { 'pt-BR': 'Outros componentes' } as Record<string, string>,
}

export const DEVELOPER_NOTES_GROUP = {
  label: 'Developer notes',
  translations: { 'pt-BR': 'Notas de desenvolvimento' } as Record<string, string>,
}

/**
 * Explicit ordering for a component's user-facing pages, keyed by the page's
 * path segment(s) relative to the project root (`docs/<repo>/<relPath>`;
 * `docs/<repo>` itself and anything under `developer-guide/` are handled
 * separately and never appear here). Docs are flattened post-migration, so
 * `relPath` is normally just the file name (e.g. `installation`), but the
 * lookup also tolerates a leading `user-guide/` segment for a project that
 * hasn't been migrated yet. Components not listed here fall back to
 * alphabetical order by slug. Any page that exists but isn't named in an
 * explicit list here is still appended (alphabetically, with a
 * `console.warn`), so nothing can silently disappear.
 */
export const COMPONENT_PAGE_ORDER: Record<string, string[]> = {
  'argvus-hyprland': ['keyboard-shortcuts', 'input', 'windows-and-layout', 'hyprland-overrides'],
  'argvus-appearance': ['wallpapers', 'fonts-and-icons', 'effects'],
  'argvus-themes': ['installing-themes', 'official-themes', 'highlight-color', 'import-and-export'],
  'argvus-session': ['graphical-session', 'tty-session'],
  'argvus-taskbar': ['taskbar', 'widgets'],
  'argvus-boot-splash': ['installation', 'usage', 'uki-splash', 'troubleshooting', 'reference', 'uninstallation'],
}

/** Boot Splash's `developer-guide/*` page order (relPath `''` = the `developer-guide` root page itself). */
export const BOOT_SPLASH_DEV_NOTES_ORDER: string[] = ['', 'theme', 'packaging', 'ci-releases', 'workflow']
